sudo: required
language: r
r_binary_packages:
 - testthat
 - digest
r_github_packages:
 - avantcredit/aws-tools
 - kirillseva/covr
 - robertzk/s3mpi
after_success:
  - "R -e 'library(covr);coveralls()'"
