sudo: required
language: r
r_binary_packages:
 - testthat
 - digest
r_github_packages:
 - avantcredit/aws-tools
 - kirillseva/covr
 - robertzk/s3mpi
after_success:
  - "R -e 'library(covr);coveralls()'"
notifications:
  hipchat:
    rooms:
      secure: C/QSVCJr0J4eLU1IF+yFOc0Az5I2oZC/F61b1Gb3OHm2ZtLTTJY+tTD1xO0PMp+FRdDLkV9PpFWei3C+tPOMVQrzHgpB9YL3RCsHbghzH3C9O7eexQMEON1xh4cI+09F+N6CisIdeQYsUEaePZ2/sOGjo1tcBdwxSjKttGslZlw=
    on_success: change
    on_failure: change
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
